---
- name: Setup Ubuntu 24 Desktop
  hosts: localhost
  become: true
  vars:
    username: "{{ ansible_user_id }}"
    home: "/home/{{ username }}"
    node_version: "20.15.1"
    python_version: "3.12.4"

  tasks:
    - name: Update and upgrade apt packages
      ansible.builtin.apt:
        upgrade: dist
        update_cache: true

    - name: Install essential packages
      ansible.builtin.apt:
        pkg:
          - build-essential
          - git
          - curl
          - wget
          - vim
          - tmux
          - jq
          - unzip
          - software-properties-common
          - apt-transport-https
          - gnupg

    - name: Install Docker
      block:
        - name: Remove old Docker GPG key
          ansible.builtin.file:
            path: /etc/apt/trusted.gpg.d/docker.gpg
            state: absent

        - name: Remove old Docker repository files
          ansible.builtin.file:
            path: "{{ item }}"
            state: absent
          loop:
            - /etc/apt/sources.list.d/docker.list

        - name: Remove old Docker keyring
          ansible.builtin.file:
            path: /usr/share/keyrings/docker-archive-keyring.gpg
            state: absent

        - name: Create Docker keyring directory
          ansible.builtin.file:
            path: /etc/apt/keyrings
            state: directory
            mode: '0755'

        - name: Add Docker GPG apt Key
          ansible.builtin.get_url:
            url: https://download.docker.com/linux/ubuntu/gpg
            dest: /etc/apt/keyrings/docker.asc
            mode: '0644'

        - name: Add Docker Repository
          ansible.builtin.apt_repository:
            repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
            state: present
            filename: docker

        - name: Install Docker
          ansible.builtin.apt:
            pkg:
              - docker-ce
              - docker-ce-cli
              - containerd.io
              - docker-compose-plugin
            update_cache: true

        - name: Add user to docker group
          ansible.builtin.user:
            name: "{{ username }}"
            groups: docker
            append: true

    - name: Install snap packages (strict mode)
      community.general.snap:
        name:
          - code
          - libreoffice
          - evince
          - discord
          - telegram-desktop
          - vlc
          - obs-studio
          - termius-app
          - postman
          - bitwarden
          - pinta
          - brave
        state: present

    - name: Install snap packages (classic mode)
      community.general.snap:
        name: "{{ item }}"
        classic: true
        state: present
      loop:
        - intellij-idea-ultimate
        - datagrip
        - phpstorm
        - webstorm
        - pycharm-professional
        - kubectl
        - zaproxy

    - name: Remove old Chrome repository files
      ansible.builtin.file:
        path: /etc/apt/sources.list.d/google-chrome.list
        state: absent

    - name: Add Google Chrome repository
      ansible.builtin.apt_repository:
        repo: deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
        state: present
        filename: google-chrome

    - name: Add Google Chrome GPG key
      ansible.builtin.apt_key:
        url: https://dl.google.com/linux/linux_signing_key.pub
        state: present

    - name: Install Google Chrome
      ansible.builtin.apt:
        name: google-chrome-stable
        state: present
        update_cache: true

    - name: Install Thunderbird
      ansible.builtin.apt:
        name: thunderbird
        state: present

    - name: Install Firefox
      ansible.builtin.apt:
        name: firefox
        state: present

    - name: Install OpenVPN3
      block:
        - name: Remove old OpenVPN repository files
          ansible.builtin.file:
            path: /etc/apt/sources.list.d/openvpn-packages.list
            state: absent

        - name: Create OpenVPN keyring directory
          ansible.builtin.file:
            path: /etc/apt/keyrings
            state: directory
            mode: '0755'

        - name: Add OpenVPN3 GPG key
          ansible.builtin.get_url:
            url: https://swupdate.openvpn.net/repos/openvpn-repo-pkg-key.pub
            dest: /etc/apt/keyrings/openvpn.asc
            mode: '0644'

        - name: Add OpenVPN3 Repository
          ansible.builtin.apt_repository:
            repo: >-
              deb [arch=amd64 signed-by=/etc/apt/keyrings/openvpn.asc]
              https://packages.openvpn.net/openvpn3/debian {{ ansible_distribution_release }} main
            state: present
            filename: openvpn-packages

        - name: Update apt cache
          ansible.builtin.apt:
            update_cache: true

        - name: Install OpenVPN3
          ansible.builtin.apt:
            name: openvpn3
            state: present

    - name: Configure UFW
      community.general.ufw:
        rule: allow
        port: '22'
        proto: tcp

    - name: Enable UFW
      community.general.ufw:
        state: enabled
        policy: deny

    - name: Download Zoom .deb package
      ansible.builtin.get_url:
        url: https://zoom.us/client/latest/zoom_amd64.deb
        dest: /tmp/zoom_amd64.deb
        mode: '0644'

    - name: Install Zoom from .deb package
      ansible.builtin.apt:
        deb: /tmp/zoom_amd64.deb
        state: present

    - name: Clean up Zoom .deb package
      ansible.builtin.file:
        path: /tmp/zoom_amd64.deb
        state: absent

    - name: Install Nmap
      ansible.builtin.apt:
        name: nmap
        state: present

  handlers:
    - name: Restart Docker
      ansible.builtin.service:
        name: docker
        state: restarted
